# Generated by Django 4.2 on 2023-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_money_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enter_your_username", models.CharField(max_length=50)),
                ("enter_destination_username", models.CharField(max_length=50)),
                ("enter_amount_to_request", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="money", name="amount", field=models.IntegerField(default=1000),
        ),
    ]
