# Generated by Django 4.2 on 2023-04-28 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_money_user_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="money",
            name="currency",
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
